## Ping server
GET http://localhost:3000/ping HTTP/1.1
content-type: application/json

### login
POST http://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "email": "user1@eg.com",
    "password": "user1@pass"
}

### Creating users
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU

{
    "email": "user1@eg.com",
    "password": "user1@pass",
    "role": "TEACHER"
}

### Get all active users
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU

### Get all active users
POST  http://localhost:3000/api/schools HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU

{
    "level": "BASIC",
    "name":  "Dan Ibu Int",
    "regd_no": "0001",
    "address": "Kpaguri",
    "phone": "020000000",
    "city": "Wa",
    "region": "UW"
}

### Get all active users
GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU

### Update school
PUT  http://localhost:3000/api/schools/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU

{
    "motto": "Knowdlege is power"
}

### Get all active users
GET http://localhost:3000/api/schools HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBlZy5jb20iLCJyb2xlIjoiQURNSU4iLCJhY3RpdmUiOnRydWUsImlhdCI6MTY5ODU3MDk2Nn0.JIceHIqQ4Y-A_piPpAxvqK7lMvv0kuYarrN7EgR8gfU
